export const FETCH_REPOS = "FETCH_REPOS"
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS"
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE"



export const FETCH_USER_DETAILS = "FETCH_USERS"
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USERS_SUCCESS"